workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    environment:
      android_signing:
        - keystore_reference
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "esim_webview_host/ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.tung1506.esimwebviewhost"
        
      # ✅ FIX: Specify exact Flutter version
      flutter: 3.24.5  # ← Change from 'stable' to specific version
      xcode: 15.4
      cocoapods: default
      
    scripts:
      - name: Get Flutter packages for flutter_esim
        script: |
          cd flutter_esim
          flutter pub get
          
      - name: Get Flutter packages for esim_webview_host
        script: |
          cd esim_webview_host
          flutter pub get
          
      - name: Set up code signing
        script: |
          cd esim_webview_host
          xcode-project use-profiles
          
      - name: Install CocoaPods
        script: |
          cd esim_webview_host/ios
          pod install
          
      - name: Build IPA
        script: |
          cd esim_webview_host
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
            
    artifacts:
      - esim_webview_host/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true
          
  # ✅ ADD: Android workflow for testing
  android-workflow:
    name: Android Build (Test)
    max_build_duration: 60
    instance_type: mac_mini_m1
   
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
      
    scripts:
      - name: Get Flutter packages for flutter_esim
        script: |
          cd flutter_esim
          flutter pub get
          
      - name: Get Flutter packages for esim_webview_host
        script: |
          cd esim_webview_host
          flutter pub get
          
      - name: Build Android APK
        script: |
          cd esim_webview_host
          flutter build apk --debug
          
    artifacts:
      - esim_webview_host/build/app/outputs/flutter-apk/*.apk